const express = require('express');
const axios = require('axios');
let books = require("../booksdb.js");
let isValid = require("./auth_users.js").isValid;
let users = require("./auth_users.js").users;

const public_users = express.Router();

// TASK 10: Get All Books using Async/Await
public_users.get('/async-books', async (req, res) => {
    try {
            const getBooks = () => {
                        return new Promise((resolve) => resolve(books));
                                };
                                        const allBooks = await getBooks();
                                                return res.status(200).json(allBooks);
                                                    } catch (err) {
                                                            return res.status(500).json({ message: "Error fetching books" });
                                                                }
                                                                });

                                                                // TASK 11: Get Book by ISBN using Async/Await
                                                                public_users.get('/async-isbn/:isbn', async (req, res) => {
                                                                    try {
                                                                            const isbn = req.params.isbn;
                                                                                    const getBook = () => {
                                                                                                return new Promise((resolve, reject) => {
                                                                                                                if (books[isbn]) {
                                                                                                                                    resolve(books[isbn]);
                                                                                                                                                    } else {
                                                                                                                                                                        reject("Book not found");
                                                                                                                                                                                        }
                                                                                                                                                                                                    });
                                                                                                                                                                                                            };
                                                                                                                                                                                                                    const book = await getBook();
                                                                                                                                                                                                                            return res.status(200).json(book);
                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                        return res.status(404).json({ message: err });
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                            // TASK 12: Get Books by Author using Async/Await
                                                                                                                                                                                                                                            public_users.get('/async-author/:author', async (req, res) => {
                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                        const author = req.params.author.toLowerCase();
                                                                                                                                                                                                                                                                const getBooksByAuthor = () => {
                                                                                                                                                                                                                                                                            return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                            let filteredBooks = [];
                                                                                                                                                                                                                                                                                                            for (let key in books) {
                                                                                                                                                                                                                                                                                                                                if (books[key].author.toLowerCase() === author) {
                                                                                                                                                                                                                                                                                                                                                        filteredBooks.push({ isbn: key, ...books[key] });
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                            if (filteredBooks.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                resolve(filteredBooks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reject("No books found for this author");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const result = await getBooksByAuthor();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(200).json(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(404).json({ message: err });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // TASK 13: Get Books by Title using Async/Await
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public_users.get('/async-title/:title', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const title = req.params.title.toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const getBooksByTitle = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let filteredBooks = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (let key in books) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (books[key].title.toLowerCase() === title) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    filteredBooks.push({ isbn: key, ...books[key] });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (filteredBooks.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resolve(filteredBooks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reject("No books found with this title");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const result = await getBooksByTitle();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(200).json(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return res.status(404).json({ message: err });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    module.exports.general = public_users;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    